/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'bridal' : null } |
  { 'bestSellers' : null } |
  { 'silk' : null } |
  { 'designer' : null } |
  { 'cotton' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'timestamp' : Time,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
  'totalPrice' : Price,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface OrderItemView { 'quantity' : bigint, 'product' : Product }
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface OrderView {
  'id' : bigint,
  'status' : OrderStatus,
  'timestamp' : Time,
  'buyer' : Principal,
  'items' : Array<OrderItemView>,
  'totalPrice' : Price,
}
export type Price = bigint;
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : Price,
}
export interface ProductInput {
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : Price,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[ProductInput], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderView>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<OrderView>>,
  'getOrder' : ActorMethod<[bigint], [] | [OrderView]>,
  'getOrdersByUser' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>], bigint>,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];